Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "rum")
Ingredient.create(name: "gin")
Ingredient.create(name: "vodka")
Ingredient.create(name: "whiskey")
Cocktail.create(name: "Whiskey Sours")
Cocktail.create(name: "Gin and Tonic")
Cocktail.create(name: "Old Fashioned")
Cocktail.create(name: "Amaretto Sours")
Cocktail.create(name: "Screwdriver")
Dose.create(description: "2 shots")
Dose.create(description: "50ml")
Dose.create(description: "1 shot")
